/**
 * Chat (EQ Coach) types for Reflectif
 *
 * Based on arch_v2.md and context_dump.md
 *
 * Each ConversationAnalysis has its own linked Chat.
 * The EQ coach has context of that specific conversation for discussion.
 * - Has access to RAG (core user file + conversation summaries)
 * - Can update core memory based on what user shares
 * - Stateful within session; across sessions relies on RAG + core memory
 */

/**
 * A single message in a chat session.
 */
export type ChatMessage = {
  id: string;
  /** Who sent this message */
  role: 'user' | 'assistant';
  /** Message content */
  content: string;
  /** ISO timestamp */
  createdAt: string;
};

/**
 * A chat session linked to a specific conversation analysis.
 */
export type Chat = {
  id: string;
  /** The conversation analysis this chat is linked to (null for standalone chats) */
  conversationAnalysisId: string | null;
  /** ISO timestamp when chat was created */
  createdAt: string;
  /** All messages in this chat */
  messages: ChatMessage[];
};

/**
 * A suggested conversation topic for the "Observe Yourself" page.
 * Generated by Backboard (memory:read) → Gemini structured extraction.
 */
export type TopicSuggestion = {
  /** Short display text, e.g. "Evening anxiety patterns" */
  label: string;
  /** One sentence explaining why this topic is relevant */
  description: string;
  /** Hidden context prepended to the first message when user clicks this topic */
  contextPrompt: string;
};

/**
 * Lightweight version for sidebar list.
 */
export type ChatListItem = {
  id: string;
  /** The conversation analysis this chat is linked to */
  conversationAnalysisId: string;
  /** Preview text (first message or summary) */
  preview: string;
  /** ISO timestamp */
  createdAt: string;
};
