/**
 * Conversation analysis types for Reflectif
 *
 * Based on arch_v2.md - single LLM call produces one ConversationAnalysis object.
 * No artificial separation into independent types.
 */

/**
 * A semantic phase/segment of a conversation identified by the LLM.
 * Not fixed-length time buckets - actual shifts in what's happening.
 * Granularity is up to the LLM (a 5-min chat might have 2 phases, a 30-min argument might have 8).
 */
export type ConversationPhase = {
  /** Human-readable label for this segment, e.g. "Disagreement about deadline" */
  phase: string;
  /** Why the LLM identified this as a distinct phase (what shifted) */
  reason: string;
  /** Emotional characterization of this phase, freeform */
  mood: string;
  /** Optional observation or actionable suggestion specific to this phase */
  insight: string | null;
  /** Seconds from conversation start (absolute) */
  startTime: number;
  /** Seconds from conversation start (absolute) */
  endTime: number;
};

/**
 * Predetermined emoji set for conversation tone.
 * LLM picks one based on overall tone.
 */
export const CONVERSATION_EMOJIS = [
  '😊', // Warm/Positive
  '😰', // Anxious
  '😤', // Frustrated
  '😢', // Sad
  '😎', // Confident
  '😐', // Neutral
  '😴', // Low energy
  '🤔', // Thoughtful/Uncertain
] as const;

export type ConversationEmoji = typeof CONVERSATION_EMOJIS[number];

/**
 * Full analysis output for a single conversation.
 * Generated by one LLM call. Scores come from Hume.ai, everything else from LLM.
 */
export type ConversationAnalysis = {
  /** Unique identifier for this analysis */
  id: string;
  /** ISO timestamp when analysis was created */
  analyzedAt: string;
  /** One paragraph overview of the entire conversation */
  summary: string;
  /** From predetermined set, LLM picks based on overall tone */
  emoji: ConversationEmoji;
  /** 1-2 word emotional tone label, e.g. "Tense", "Warm", "Draining" */
  label: string;
  /**
   * LLM-segmented phases of the conversation based on semantic context.
   * Not fixed-length time buckets - actual shifts in what's happening.
   */
  dynamics: ConversationPhase[];
  /**
   * Timestamped emotion series from Hume.ai.
   * Timestamps are absolute (seconds from conversation start).
   *
   * TODO: Type will be TimestampedEmotionScores[] once Hume.ai integration is done.
   * For now using any[].
   */
  scores: any[];
  /**
   * Communication patterns observed in THIS conversation.
   * e.g. "deflects with humor when challenged", "interrupts when anxious"
   * These are also tracked at the progress level across conversations.
   */
  patterns: string[];
};

/**
 * Lightweight version for list views (sidebar, history)
 */
export type ConversationAnalysisListItem = Pick<
  ConversationAnalysis,
  'id' | 'analyzedAt' | 'emoji' | 'label' | 'summary'
>;
