/**
 * Progress and EQ tracking types for Reflectif
 *
 * Based on arch_v2.md - measures EQ growth, not emotional polarity.
 * The app is an EQ trainer, not a mood tracker.
 */

/**
 * Fixed set of EQ dimensions for consistent charting over time.
 *
 * Modified Goleman with Bar-On correction: replaced 'motivation' (unobservable
 * in conversation) with 'stress_management' (directly measurable via prosody).
 */
export const EQ_DIMENSION_NAMES = [
  'self_awareness',
  'self_regulation',
  'empathy',
  'social_skills',
  'stress_management',
] as const;

export type EQDimensionName = typeof EQ_DIMENSION_NAMES[number];

/**
 * A single EQ dimension with score and trend.
 */
export type EQDimension = {
  /** Fixed set for consistent charting over time */
  name: EQDimensionName;
  /** 0-1, LLM-assigned based on evidence in the lookback window */
  score: number;
  /** Freeform, e.g. "Improving steadily", "Stagnant since January" */
  trend: string;
};

/**
 * A concrete improvement the user has made.
 * Evidence is quoted excerpts from past conversations.
 */
export type ProgressPoint = {
  /** What improved, e.g. "Started acknowledging partner's perspective" */
  observation: string;
  /** Quoted excerpts as evidence, e.g. "'You started by asking about their day' - Oct 15" */
  evidence: string[];
};

/**
 * An area that still needs work.
 * Evidence is quoted excerpts from past conversations.
 */
export type ImprovementArea = {
  /** What still needs work, e.g. "Shuts down during financial discussions" */
  observation: string;
  /** Quoted excerpts as evidence */
  evidence: string[];
  /** Actionable recommendation */
  suggestion: string;
};

/**
 * Full progress report for a user.
 * Generated by single LLM call with RAG context (past conversation summaries + core user file).
 * Endpoint accepts lookback window parameter (null = all time).
 */
export type UserProgress = {
  /** Structured EQ scores for visualization/charting */
  eq: EQDimension[];
  /** Concrete improvements made, with evidence from past conversations */
  progress: ProgressPoint[];
  /** Specific EQ gaps still present, with evidence and actionable suggestions */
  improvements: ImprovementArea[];
};
